### PR TITLE
Resolve Configuration Error

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #547

### CODE REVIEW

**Comment by imran3004** [comment]
@Jeff-Thompson12 , I see that there's a warning and the UI is fired up. But the inputs, such as text box for entering package names, are disabled. Is this expected behaviour?

**Comment by Jeff-Thompson12** [comment]
> @Jeff-Thompson12 , I see that there's a warning and the UI is fired up. But the inputs, such as text box for entering package names, are disabled. Is this expected behaviour?

It is expected behavior if you are not running the application with `add_package` privileges. Did you reinitialized your credentials and assessment databases?

**Comment by Jeff-Thompson12** [comment]
@imran3004 Upon further review, it is expected behavior because in the example configuration the admin user does not have privileges to add packages.

**Comment by imran3004** [comment]
> @imran3004 Upon further review, it is expected behavior because in the example configuration the admin user does not have privileges to add packages.

Thanks @Jeff-Thompson12 ! Please can you also update the dev version and the News file?

**Review by AARON-CLARK — APPROVED** [review]
It's my privilege to serve in the approver role for this PR.

**Pull request merged**
