### PR TITLE
Update db-config.yml

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
This PR changes the configuration of decision categories and rules to be a list instead of separate values. I believe this will aid in adding more complexity down the road (e.g. metric weights, colors, etc.)

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
Hmm...it looks like you might have highlighted an unintended issue without realizing it. I think the reason it is not working is because of the indents. `rules` is a subcategory of `decisions`.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Do you think this is an issue that can be corrected with documentation? I could also send a message to the console. I think we want to move away from people initializing the application with `riskassessment::run_app()` anyways. Thankfully we have the initialization already written as a function.

**Comment by AARON-CLARK** [comment]
> Do you think this is an issue that can be corrected with documentation? I could also send a message to the console.

Yes, both! Some sort of warning (or error) message should probably be thrown.

**Comment by Jeff-Thompson12** [comment]
I think the documentation should wait until we finish adding the other items to `db-config.yml` from our roadmap.

I have added some simple checks to let the user know that unexpected behavior may have occurred.

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
This config file didn't produce any messaging in the console:
```yml
default:
  assessment_db: database.sqlite
  credential_db: credentials.sqlite
  decisions:
    categories:
      - Low Risk
      - Medium Risk
      - High Risk
  rules:
    Low Risk:
      - 0
      - .1
    High Risk:
      - .7
      - 1
```

image

**Review by AARON-CLARK — APPROVED** [review]
Just kidding! Works like a charm!

**Pull request merged**
