### PR TITLE
Disable Roles for Editing Multiple Users

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #543

### CODE REVIEW

**Comment by imran3004** [comment]
Not sure if I understand the issue. @AARON-CLARK , please can you review the PR?

**Comment by AARON-CLARK** [comment]
> Not sure if I understand the issue. @AARON-CLARK , please can you review the PR?

Hi @imran3004, for context: 
https://github.com/pharmaR/riskassessment/issues/543#issuecomment-1594966229


After testing, this selectInput was successfully removed. I'll update the version & add a news bullet point, then merge.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK why no merge?

**Review by AARON-CLARK — APPROVED** [review]
merge time!

**Pull request merged**
