### PR TITLE
Disable MRAN

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
Attempting to disable the MRAN config without updating all the packages to see if GHAs will pass.

**Comment by AARON-CLARK** [comment]
👍🏼

**Comment by Jeff-Thompson12** [comment]
I also got rid of the other OS checks (windows and mac) on the master branch.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Can you give this a look? I only listed you as a reviewer since it is editing our GHAs.

**Review by AARON-CLARK — APPROVED** [review]
LGTM!

**Pull request merged**
