### PR TITLE
Rk 147 user guide

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
Adding a user guide and a vignettes folder

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
Hi @Robert-Krajcik, I see all tests as passing:

image

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK 
Not sure what was going on this morning, but whatever it was resolved itself.
I'm not adding any tests here, just a vignette.   
I think it's a pretty complete walk-through of `riskmetric`

**Review by AARON-CLARK — COMMENTED** [review]
Hi @Robert-Krajcik, this is a great start! As mentioned previously, I wanted to expand on what you put together, so I made a new PR for you to review. 

Second, I wanted to mention that according to `pkgdown` documentation, we need to name this vignette after the name of the package, so: "riskassessment.Rmd" and it will automatically create the 'Get Started' tab and populate it with this vignette.

Last, don't worry too much about how wide certain images are in the vignette, those will automatically get scaled down per `pkgdown`.

Please see PR #349

**Comment by AARON-CLARK** [comment]
Hi @Robert-Krajcik, thanks again for this PR, but I'm going to close it for now given we're collaborating on #349, which augments this PR.

**Pull request closed without merging**
