### PR TITLE
Rk 417 pkg names

### LINKED ISSUE #417: Don't alter case on pkg names
We should avoid messing with the capitalization of package names, since they are case sensitive. Note: I'm pretty sure this is happening by default thanks to our `{bslib}` theme selection. The below snapshot is from an html report, but altered case may exist in other areas of the app.

image

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
closes #417

### CODE REVIEW

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Hi @Robert-Krajcik, this looks really good! Wondering if you could also make this text "asis" as well? And maybe add the curly braces onto `riskmetric`? 

image

I tried all three report types, and it looks like HTML is the only one effected. Here's the Word and PDF output:

image

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK 
Yes I can take a look at this in a short while.
I think these uppercase are coming from `mod_downloadhandler.R`

**Comment by Robert-Krajcik** [comment]
Ready for another review, @AARON-CLARK

**Review by AARON-CLARK — APPROVED** [review]
Looks good!
image

**Pull request merged**
