### PR TITLE
Add user name to batch upload

### LINKED ISSUE #785: Attached username to batch upload decisions
Thinking about the batch upload process again. I feel like we need to include the username in the "Decision by" column on the database overview tab just in case an org wants to track that. So for example, it should read "Aaron (Batch Upload)". What do you think?

I was just thinking of a use case where there are several people able to run a "pkg approval process" outside of the app on new requested packages. Sometimes its done on large quantities of packages, but other times it may only be done on like 10 pkgs. It would be nice for us to know who uploaded those 10 pkgs to the app for auditing purposes.

Currently, the table looks like this, simply stating "Batch upload"

image

### PR DESCRIPTION
**Pull request by jthompson-arcus**
Closes #785

### CODE REVIEW

**Comment by jthompson-arcus** [comment]
User name is now added as a parenthetical to the batch upload designation.
image

**Review by aclark02-arcus — APPROVED** [review]
This looks good as-is. The only change I'd suggest is allowing users to make a decision when using `upload_pkg_list()` but I think that task can be saved for another day! I'll create a new issue for it. Thanks!

**Comment by jthompson-arcus** [comment]
> This looks good as-is. The only change I'd suggest is allowing users to make a decision when using `upload_pkg_list()` but I think that task can be saved for another day! I'll create a new issue for it. Thanks!

Like if `is.null(user_name)` then just record it as `Batch Upload` instead of defaulting to `Batch Upload (system)`?

**Comment by aclark02-arcus** [comment]
@Jeff-Thompson12, no. I mean't adding a new arg, called `decision` to that function. So it could be used like:

`upload_pkg_list(c("Tplyr","dplyr","dbplyr"), decision = c("Medium Risk", "Low Risk", ""))`

Just a suggestion.

**Pull request merged**
