### PR TITLE
Fixes issue for colorblind users

### PR DESCRIPTION
**Pull request by AARON-CLARK**
See examples in #324 for the 'before image' but the database tab looks like the below image with this changes in this PR. Notice, I had to dynamically change the color of the font in some areas. Overall, I tend to like the old color gradient better, but this is confirmed to work with our colorblind users.

image

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK This is probably the request you were dreading to hear, but can we make this a toggleable option?

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK This is probably the request you were dreading to hear, but can we make this a toggleable option?

@Jeff-Thompson12, I suppose it could be. But why? Because we liked the other color scheme better? I'm not opposed.

**Comment by Jeff-Thompson12** [comment]
Part of me wonders why not go the whole way and let users select their own palette, but I suppose simpler is better. I guess there is no compelling reason to toggle an "accessibility" view.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12 mentioned it may be nice to have other visual indicators besides colors, like an exclamation point or a thumbs up or emoji faces next to the each decision.

**Comment by AARON-CLARK** [comment]
So, good news, I'm told that if you darken a colorblind-friendly palette, they can still perceive the gradient. So I think this is a happy compromise and doesn't look oppressively bright. Thoughts @Jeff-Thompson12?

image

**Review by Jeff-Thompson12 — APPROVED** [review]
I like the more muted colors. I still think it could be nice to have some form a visual indicators outside of color, but that feels like a different PR/issue.

**Pull request merged**
