### PR TITLE
Modify `renv` Rmd vignette

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Provides more context to developers for onboarding purposes. Did I accurately describe a decent `renv` workflow when working amongst several developers?

### CODE REVIEW

**Review by Xyarz — APPROVED** [review]

**Comment by Xyarz** [comment]
@AARON-CLARK PR is approved, the changes do look fine. Thanks for the enhanced docu. Not sure why some tests related to the db do fail tho.

**Comment by AARON-CLARK** [comment]
So, after working through some CI bugs, I ended up making a few changes to the `renv.lock` file:
1. reverted back to `R v4.1.2` from `v4.2.2` until @Xyarz gains access to a more recent 

1. Also, I ran `renv::snapshot()` to try and add my github branch's version of the `riskassessment` package using `remotes::install_github("pharmaR/riskassessment", ref = "ac-modify-renv-rmd")` but it kept failing saying the `{xfun}` didn't exist. How else are we supposed to test the current branch in our CI/CD? Or does CI/CD compile the package and ignore the `renv.lock` file for GHA?

1. Anyway, I abandoned that approach due to the `{xfun}` issue, but I noticed it changed all the repo statements to 'RSPM' instead of 'CRAN'. I'm not sure why that happened because the only repo I have stored is:

image

**Comment by AARON-CLARK** [comment]
To solve # 3, I was able to remove `riskassessment` from the lock file and just have our CI/CD checks install `riskassessment` by mimicking [this renv workflow](https://github.com/rstudio/renv/blob/main/.github/workflows/R-CMD-check.yaml#L102-L104) (thanks @borgmaan)! Please see commit [feda9f1](https://github.com/pharmaR/riskassessment/pull/398/commits/feda9f16240c98e2694cae288517aa1721939404) to see the change. I think this works well!

@Xyarz or @borgmaan, if you are okay with # 4, then I think this PR is ready to merge.

**Comment by AARON-CLARK** [comment]
> Not sure if we need the [other stuff](https://github.com/rstudio/renv/blob/main/.github/workflows/R-CMD-check.yaml#L106-L117) they use. Any thoughts?

Chatted with folks offline and they confirmed we don't need additional "stuff". Merging since PR was approved prior to changes.

**Pull request merged**
