### PR TITLE
Correctly parse `riskmetric` dependency assessment

### LINKED ISSUE #805: Inaccurate display of number of dependencies
https://github.com/pharmaR/riskassessment/blob/a199a2eb8d0b7dae651c8d90df94e745e1d983f0/R/utils_insert_db.R#L205

If a package has 0 dependencies, `riskmetric` returns `character(0)` for the assessment value, but this code effectively renders it as `NA` which has a length of 1 instead of 0.

### PR DESCRIPTION
**Pull request by jthompson-arcus**
Closes #805

### CODE REVIEW

**Comment by jthompson-arcus** [comment]
The change in metric calculation is more inline with how the [score is being calculated](https://pharmar.github.io/riskmetric/reference/metric_score.pkg_metric_dependencies.html) as well with using `NROW()`.

**Comment by aclark02-arcus** [comment]
Was this PR supposed to synchronize `gower` too?

image

image

**Comment by jthompson-arcus** [comment]
Yes, did you re-upload the package? It should be showing 0 dependencies.

**Comment by aclark02-arcus** [comment]
> Yes, did you re-upload the package? It should be showing 0 dependencies.
> 
> You have to re-upload because the value is being written to the database.

Whoops, nope. For some reason, I was expecting the table to show one dep instead of the other way around (card showing 0 deps). Sorry

**Review by aclark02-arcus — APPROVED** [review]
💪🏼 
Looks good to me

**Pull request merged**
