### PR TITLE
Fix GHAs for DOCX and PDF downloads

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #702

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
I have investigated printing the HTML reports to PDF. While some improvements can be made to make the reports nicer to print interactively, I do not think the work to get the reports to work programmatically is worth the effort (at least not in the short term).

Efforts would be better suited to determining which LaTeX packages are necessary to be able to print the DOCX and PDF versions of the report and to provide some user feedback if those packages are missing from the environment where the application is running.

**Comment by Jeff-Thompson12** [comment]
I was able to get the PDF reports to work on the GHAs by installing the `texlive-xetex` package to get XeLatex.

**Comment by Jeff-Thompson12** [comment]
I think this gives us a path forward to getting the downloads to work in deployments. Hopefully the steps to get the downloads to work on the GHAs  will be similar to what will be needed on the deployment servers. The downside is that users will have to get their respective admins to install the necessary dependencies.

**Comment by AARON-CLARK** [comment]
To summarize a discussion with @Jeff-Thompson12 offline: 

> It's still on draft because I haven't actually fully resolved the deployment downloads.

> I still have not created guidance for setting up that environment so that the reports can download...

>... or figuring out how to determine if a report can compile. I feel like at least we should disable downloads that can't compile (if we can). Aka, provide some user feedback if those packages are missing from the environment where the application is running.

**Comment by Jeff-Thompson12** [comment]
Per discussion today, I am changing the scope of this PR since the changes made benefit our workflow. I will open a new PR to tackle the download issues when the app is deployed.

**Review by Robert-Krajcik — APPROVED** [review]
LGTM

**Pull request merged**
