### PR TITLE
Spell Check!

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Adds some progress to #270
PR accomplishes:
* fixes existing spelling errors in package files, including vignettes
* set spelling unit test to error when a new misspelled word is found

### CODE REVIEW

**Review by borgmaan — DISMISSED** [review]
Looks good to me and I'm happy to merge as is. However, I'm wondering if you know why none of the CI checks are showing up in the PR?

**Comment by AARON-CLARK** [comment]
> I'm wondering if you know why none of the CI checks are showing up in the PR?

@borgmaan I'm not really sure! I just pushed a dummy commit and it looks like they are running again.

**Comment by AARON-CLARK** [comment]
Whoops, need to get #373 through first.

**Review by borgmaan — APPROVED** [review]
👍

**Pull request merged**
