### PR TITLE
Tests for databaseView[UI/Server]

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Adds tests for the `databaseView` module. Adjustments to the app code has been made where necessary to enable more full testing.

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
Running into issues with the download handler if any helpful soul has input.

**Comment by Jeff-Thompson12** [comment]
I know tests are failing. They don't seem to be related to my PR though. If you know better, please enlighten me.

**Review by Robert-Krajcik — APPROVED** [review]
After that last push,
All your tests pass,
and (after I install riskmetric) the `devtools::check()` comes back clean (just two notes)
one GHA test fails, but its something we merged two days ago (codecov/patch)

**Comment by Jeff-Thompson12** [comment]
@borgmaan & @AARON-CLARK did either of you want to take look at this PR or is @Robert-Krajcik good to merge?

**Review by borgmaan — APPROVED** [review]
Sorry for the delay -- looks good to me!

**Pull request merged**
