### PR TITLE
Augment Robert's User guide + add branding images

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Built upon #335 (Thanks @Robert) and makes progress on #147.

When you knit the `riskassessment.Rmd` file, don't worry too much about how wide certain images are in the vignette, those will automatically get scaled down per `pkgdown`.

I also updated the `README` with some sexy `riskmetric` and `riskassessment` hex stickers, but I also changed the favicon and added some imagery in-app. Here are some snapshots...

image

image

image

image

I would love to solicit someone's help to get that last one up into the top-level `tabsetPanel()`. Or thoughts on if we even need that image? Perhaps something on the auth page would suffice?

### CODE REVIEW

**Review by Robert-Krajcik — CHANGES_REQUESTED** [review]
Well you have now covered every square inch of this package, @AARON-CLARK 

My only requested change is about the 'Administrative tools` tab.
There are two sub-tabs on this page.
One is the `Credential Manager` while the other is `Assessment Reweighting`

You describe the Credential Manager tab while showing the Assessment Reweighting.

I think you should describe both tabs here and have snaphots of each one.

I assume we can go back and put in the {"insert links here"] at a later time.

**Comment by AARON-CLARK** [comment]
Thanks for the review @Robert-Krajcik. I added your suggestion in commit 7335df6.

image

I'll convert this to draft while I figure out why R CMD Check was failing.

**Comment by AARON-CLARK** [comment]
Okay @Robert-Krajcik, she should be ready for review again. One of the vignette pngs was "non-portable" since it had a space in the name. So, the R CMD Check should not fail.

**Review by Robert-Krajcik — DISMISSED** [review]
Looks great @AARON-CLARK

**Review by Robert-Krajcik — APPROVED** [review]
Looks good to me

**Pull request merged**
