### PR TITLE
Add Administrative Tools and Options vignette

### PR DESCRIPTION
**Pull request by Robert-Krajcik**
Revising the older "managing userid and passwords" vignette.
Although I'm thinking about calling this "Administrative Tools and Options"
and covering both the "Credential Manager" and "Assessment Reweighting" tabs.

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
test coverage was failing. Re-running...

**Comment by AARON-CLARK** [comment]
Coverage test passing with re-run

**Comment by AARON-CLARK** [comment]
@Robert-Krajcik you have a merge conflict here.

**Comment by Robert-Krajcik** [comment]
resolved that conflict, @AARON-CLARK

**Review by AARON-CLARK — APPROVED** [review]
Hi @Robert-Krajcik, thanks the vignette! I pushed a big commit with some of my edits. I think it's ready to go, so I'll approve the PR, but could you please take a look at it to see my changes? Also I'm wondering if this might be better separated into 2 separate vignettes, one for credentials and one for metric re-weighting. What do you think?

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK 
Just some tweaks with centering the smaller boxes.
I knew you would have some input on this, and it looks fine to me as it is.

**Review by AARON-CLARK — APPROVED** [review]
💪🏼 👍🏼

**Pull request merged**
