### PR TITLE
Remove developer credentials for release

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**

### CODE REVIEW

**Review by Robert-Krajcik — DISMISSED** [review]
Looks good to me.

**Comment by Jeff-Thompson12** [comment]
Wait just a sec because I'm going to take care of a R CMD check note first before merging

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik there shouldn't be any harm in merging even though the tests haven't been completed. All I did was add words to our list of global variables.

**Review by Robert-Krajcik — APPROVED** [review]
LGTM

**Pull request merged**
