### PR TITLE
Rk 378 add logo2 docxpdf

### PR DESCRIPTION
**Pull request by Robert-Krajcik**

### CODE REVIEW

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK 
I haven't updated the renv lockfile yet, but I am currently using `{rmarkdown}` 2.20.1 and `{tinytex}` 0.44.1

One thing I found about using latex, in
https://bookdown.org/yihui/rmarkdown-cookbook/latex-header.html

`By default, headers and footers will not be displayed on the first page of your PDF document. If we wish to show our footer on the front page, we must include an additional line \fancypagestyle{plain}{\pagestyle{fancy}}`

**Comment by Robert-Krajcik** [comment]
look at https://github.com/rstudio/tinytex-releases
I used
remotes::install_github('rstudio/tinytex')

**Comment by Robert-Krajcik** [comment]
One more thing to debug:
`! LaTeX Error: Unicode character ≥ (U+2265)
               not set up for use with LaTeX.
`

**Comment by Robert-Krajcik** [comment]
OK It's working again.  added different latex engine and unicode-math pack

**Comment by AARON-CLARK** [comment]
With last commit, I shifted the logo down just a tad by editing `header.docx`'s header & margins.

### Old
image


### New
image

**Comment by AARON-CLARK** [comment]
With last commit, I shifted the title (and other content) up by shrinking the header.

### Old
image

### New
image


Also, with the last commit, I made sure the metric weights table at the bottom were left justified to match the rest of the content in this section (and also matches the docx report):

### Old
image

### New
image

**Review by AARON-CLARK — APPROVED** [review]
👍🏼 Looks great!

**Pull request merged**
