### PR TITLE
Add comment module to function explorer

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #643

### CODE REVIEW

**Review by AARON-CLARK — CHANGES_REQUESTED** [review]
Hi @Jeff-Thompson12, this is looking good, BUT I have a qualm shared below:

### PDF download spins into eternity

PDF rendering get's stuck. I know this wasn't the case a few weeks ago when I was working on adding the `metric_score` to the PDF document. I did not test on `devel` but I will be optimistic and assume it's still working there because "why shouldn't it be?"

image

Can you look into this?

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK Can you tell me which preferences you had selected for the report output?

**Comment by Robert-Krajcik** [comment]
Hi @Jeff-Thompson12 
You might need to merge in the latest changes in dev

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK Can you tell me which preferences you had selected for the report output?

@Jeff-Thompson12, all elements were included / checked.

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK It appears that the usage of `kableExtra` for constructing the community usage metrics could cause the download to go into limbo. I have opted to remove it since we need a more elegant solution anyways.

**Review by AARON-CLARK — APPROVED** [review]
👍🏼 👍🏼

**Pull request merged**
