### PR TITLE
Fix application crash

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #741 in part. Does not add tests but seeks to fix current crashes.

### CODE REVIEW

**Review by Robert-Krajcik — APPROVED** [review]
Loading package `{A3}` does not crash the app with these changes.
image

**Review by AARON-CLARK — APPROVED** [review]
Nice work @Jeff-Thompson12!

**Comment by narayanan-iyer-pfizer** [comment]
I'm not able to replicate this

**Comment by aclark02-arcus** [comment]
@narayanan-iyer-pfizer, should be resolved now. I'll close the issue - thanks!

**Pull request merged**
