### PR TITLE
Ni 707 add waiting screen

### PR DESCRIPTION
**Pull request by narayanan-iyer-pfizer**
By using Archive library, I have refactored the code in code explorer, package explorer to read tarballs in memory

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
@AARON-CLARK will take a look at tests... And @Jeff-Thompson12 volunteers too!

**Comment by Jeff-Thompson12** [comment]
@narayanan-iyer-pfizer I pushed a couple commits that should help you out with dealing with the errors. It seems like the main issue now is that `archive` is returning a different directory tree than what one would expect if the tarball was unpacked. Mainly the difference is that the directory is no longer being returned in alphabetical order which I think we would want.
image

**Comment by narayanan-iyer-pfizer** [comment]
> @narayanan-iyer-pfizer I pushed a couple commits that should help you out with dealing with the errors. It seems like the main issue now is that `archive` is returning a different directory tree than what one would expect if the tarball was unpacked. Mainly the difference is that the directory is no longer being returned in alphabetical order which I think we would want. image
Thanks ! I have updated code to sort it . Still the tests seems to failing

**Review by Jeff-Thompson12 — CHANGES_REQUESTED** [review]
@narayanan-iyer-pfizer I love this PR. Few comments:

- [ ] General spacing and formatting of function calls. We don't have a formal style, but all of the other code has consistent spacing (and I personally find it easier to read).
- [ ] Using reactives in a function. I can be swayed on this but I personally think the value of a reactive should be passed in functions and not the reactive itself.

**Comment by narayanan-iyer-pfizer** [comment]
Changes made to address the requests. Tests are still failing , pls take a look.thanks

**Review by Jeff-Thompson12 — CHANGES_REQUESTED** [review]
@narayanan-iyer-pfizer I am getting some console warnings when viewing help documents in the file explorer. Can you take a look?

image

**Comment by narayanan-iyer-pfizer** [comment]
> @narayanan-iyer-pfizer I am getting some console warnings when viewing help documents in the file explorer. Can you take a look?
> 
> image
 this has been addressed in a different way

**Comment by Jeff-Thompson12** [comment]
> > @narayanan-iyer-pfizer I am getting some console warnings when viewing help documents in the file explorer. Can you take a look?
> > image
> 
> this has been addressed in a different way

Marvelous. I love it.

@AARON-CLARK did you want to take a look at this PR? My additions were fairly minor, but since I did contribute, I wasn't sure if you wanted an additional pair of eyes on it.

**Review by Jeff-Thompson12 — APPROVED** [review]

**Comment by AARON-CLARK** [comment]
> did you want to take a look at this PR?

Normally, No! I trust you. But I had a minute so I just pulled it open to test anyway (lol). The source explorer is lightning fast now! Great work @narayanan-iyer-pfizer! And thanks @Jeff-Thompson12 for contributing.

**Pull request merged**
