### PR TITLE
Type Package Names

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #248

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
I did not incorporate adding a package version since that is not being taken into account in the code base. If/when that functionality is added, we can address adding a version to the selectize input.

**Review by Robert-Krajcik — DISMISSED** [review]
This looks good to me, @Jeff-Thompson12 
I see you updated the rintrojs (help) and it looks good.
And I can still enter a .csv file full of non-existent package names and that still works.

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik Great catch! It doesn't look like we were checking package names from the csv either (outside of trimming the white space). I added in some code to keep `riskmetric` from erroring out.

**Review by Robert-Krajcik — APPROVED** [review]
OK I am no longer able to break it.  Good job!

**Pull request merged**
