### PR TITLE
Re-initialize development version

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
May want to wait for GHAs to finish to be safe but should be good to go

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK You are being very cautious with this PR.

**Comment by AARON-CLARK** [comment]
You can never be too careful... pretty rigorous testing going on.

**Review by AARON-CLARK — APPROVED** [review]
👍🏼

**Pull request merged**
