### PR TITLE
Run write-manifest on PRs to `dev`

### PR DESCRIPTION
**Pull request by jthompson-arcus**
Addresses #772

### CODE REVIEW

**Review by Jeff-Thompson12 — COMMENTED** [review]
Testing comment review

**Review by Jeff-Thompson12 — DISMISSED** [review]
Testing approval review

**Review by Jeff-Thompson12 — DISMISSED** [review]
Approval testing 2

**Review by Jeff-Thompson12 — APPROVED** [review]
Testing approval 3

**Review by Jeff-Thompson12 — APPROVED** [review]
Approval testing 4

**Review by Jeff-Thompson12 — COMMENTED** [review]
Trigger event

**Review by Jeff-Thompson12 — COMMENTED** [review]
trigger event

**Comment by jthompson-arcus** [comment]
@aclark02-arcus I think the most sensible solution is to modify our PR review workflow to have reviewers wait until the write-manifest workflow has completed before completing the merge. To my knowledge there's not really a good way to mandate it in the branch protections. Of course this workflow can be adjusted if/when someone else has a better idea.

**Comment by jthompson-arcus** [comment]
@aclark02-arcus actually hold off on reviewing. I need to make sure that if the PR is behind the `dev` branch that the write-manifest workflow will fail.

**Review by Jeff-Thompson12 — DISMISSED** [review]
Testing branch behind `dev`

**Review by Jeff-Thompson12 — COMMENTED** [review]
Testing create status

**Review by Jeff-Thompson12 — APPROVED** [review]
Testing submit status

**Review by Jeff-Thompson12 — APPROVED** [review]
Test again

**Review by Jeff-Thompson12 — APPROVED** [review]
Testing

**Comment by jthompson-arcus** [comment]
@aclark02-arcus I think I finally have this in a spot for you to look at. The code will now assign a status to additional commit where the `manifest.json` file is created. We can then use this status in our branch restrictions to ensure that PRs are up to date with `dev` and that the manifest was built.

**Review by Jeff-Thompson12 — DISMISSED** [review]
Confirm new status

**Comment by jthompson-arcus** [comment]
With branch protection on we can see that we now have the out-of-date warning.

image

**Review by Jeff-Thompson12 — DISMISSED** [review]
Check that `manifest.json` doesn't get endlessly rebuilt

**Review by Jeff-Thompson12 — DISMISSED** [review]
Test if other files are changed besides manifest.json

**Review by Jeff-Thompson12 — DISMISSED** [review]
Testing

**Review by Jeff-Thompson12 — DISMISSED** [review]
Test if it still rebuilts

**Comment by jthompson-arcus** [comment]
@aclark02-arcus For some reason the checksum always updated for `.Rprofile`, so I decided to remove it from the manifest creation process. The main issue with this process is that the write-manifest is triggered after a reviewer approves the PR. The process then adds a commit which makes the review stale, requiring the reviewer to approve the request a second time as well.

Thoughts?

**Comment by jthompson-arcus** [comment]
Skipped in draft
image

**Comment by jthompson-arcus** [comment]
@aclark02-arcus I believe this has all the functionality we want now. Only negative I can think of now is that our normal checks are no longer sitting at the head of the branch.

**Review by aclark02-arcus — APPROVED** [review]
Amazing work!

**Pull request merged**
