### PR TITLE
Prep for `v0.1.0` release

### LINKED ISSUE #379: Make logo larger
image

Discussed on 1/31 dev meetup. This appears too small. It's okay if it makes the nav bar page taller.

### LINKED ISSUE #402: Prep for new (shiny conf) minor release `v0.1.0`
## Work on `devel` first:

- [x]  Make sure all final PRs are merged into `devel`
   - [x] #398 
   - [x] #401 
   - [x] #397 
   - [x] switch back to `renv.lock` file back to R `v4.1.2` (# 398)
   - [x] `pkgdown` site cleanup/ organizing
   - [x] Add note to repo README about using latest github version of (riskmetric)
   - [x] #379
   - [x] #378
       - [x] html
       - [ ] word
       - [ ] pdf
   - [x] #405 
   - [x] #416
   - [x] fix has_report_bugs_url in all the report Rmds
   - [ ] Other cleanup PRs?
- [ ]  Final PR to the `dev` branch
    - [x]  run `run_dev.R` to ensure all `.Rd` files are built
    - [x]  increment the pkg version via `usethis::use_version()` using either "patch", "minor", or "major".
    - [x]  make sure the `NEWS.md` file is up to date and reads clearly for users. Sometimes bullet points are written in a way that users wouldn't easily understand- try to correct those.
    - [x]  Read through the `README` to see if any updates are needed
    - [x]  update authorship as needed
    - [x]  perform extra `For CRAN` steps below
    - [x] fix all `TODO` items (that are within scope of the release)
    - [x] remove all pre-auth stuff
    - [ ] Try to resolve all flavors of R-CMD-CHECK failures on PR from `dev` to `master`
    - [x] Check all notes too. See if there is anything "new" you can get rid of
- [x]  Compose PR to merge `dev` into `master` with PR (if it doesn't already exist)
    - [ ] Make sure all flavors of R-CMD-CHECK are passing
    - [x]  Check all notes too. See if there is anything "new" you can get rid of
- [x]  assign a reviewer (or two) to find any issues. 
 
## After merge into `master`:
- [x] tag a new release
- [x]  Verify everything looks good on the `{riskassessment}` [doc site](https://pharmar.github.io/riskassessment/). Sometimes it doesn't! Note it may need ~ 5 mins after a merge to `master` before it updates too. Fix any issues that arise.
- [x]  Go back to the `dev` branch and run `usethis::use_version("dev")`, then re-insert `pre_auth_user` arg from commit [2798190](https://github.com/pharmaR/riskassessment/pull/414/commits/27981902523911472da2775a6f19f96e947cc67e). Then of course, finish with a `git push origin dev`
- [x]  Open a new 'Next Release' PR that compares `dev` to `master`
- [x]  deploy a new demo version of the app to shinyapps.io with
    - [x] https://rinpharma.shinyapps.io/riskassessment/
    - [x] https://rinpharma.shinyapps.io/risk_assessment/

## For CRAN
This section is based off of [r-pkgs.org](https://r-pkgs.org/release.html) and [ThinkR's prep list](https://github.com/ThinkR-open/prepare-for-cran) and even though we aren't submitting to CRAN, these are great checks to perform before any release:
- [x]  Check for downstream dependencies using `usethis::use_revdep()`
- [ ]  Update dependencies in `DESCRIPTION` using `attachment::att_amend_desc()`
- [x]  Check content of package for missing tags using `tags <- checkhelper::find_missing_tags(); View(tags)`
- [x]  check spelling with `spelling::spell_check_package()` and after making edits, add uncorrectable words to the wordlist with `spelling::update_wordlist()`
- [x]  Check URLs with `urlchecker::url_check()` and `urlchecker::url_update()`

## Non repo work

- [x] Slides
- [x] Deploy [demo app](https://rinpharma.shinyapps.io/riskassessment/)
- [x] Google Form (#411)

### PR DESCRIPTION
**Pull request by AARON-CLARK**
This PR:
* Accomplishes part of #402
* Accomplishes the html part of #378 
* Closes #379 
* Adapts reports to new has_report_bugs_url assessment value
* makes sure all .Rd files are up to date, making sure they have all the correct tags, (for example `@return` tags for exported functions)
* removed notes from R CMD Check - specifically addressed new global variables
* increments pkg to `v0.1.0`
* streamlines the `NEWS` file for better user consumption
* updates the `README` with best practice installation instructions (aka, cloning the repo)
* Fix any `TODO` items (in scope for this release)
* removes all `pre_auth_user` arg "stuff"
* checks URLs
* Fixes spelling
* re-organizes authors by "time on project", role/ status, and entity (human vs org - moving orgs to the bottom)
* moves `pkgload` to suggests as it's only needed in the `app.R` file.

### CODE REVIEW

**Comment by AARON-CLARK** [comment]
Good morning @borgmaan, @Robert-Krajcik, @Jeff-Thompson12. This "final" PR to `dev` is ready for review. Again, the ✔️ is pretty elusive thanks to `shinytest2` tests. Wondering if you all can work together to get this PR reviewed, fixed (if necessary), and merged today? I'll be OOO from 8am onward. I trust your judgement if you need to make some executive decisions while I'm out.

**Review by Jeff-Thompson12 — COMMENTED** [review]
Everything looks good. I did push a handful of edits. So I will let someone else approve.

One thing I do not like about this PR is that the `pre_auth_user` arguments have been removed. While I do not think we want to push them to `master`, I don't really want to have commits removing them from the `dev` branch. This necessitates us to commit them back in after merging `dev` to `master`.

**Review by Robert-Krajcik — APPROVED** [review]
Looks good to me!
Thanks Jeff for some last-minute updates.

**Comment by AARON-CLARK** [comment]
> One thing I do not like about this PR is that the `pre_auth_user` arguments have been removed. While I do not think we want to push them to `master`, I don't really want to have commits removing them from the `dev` branch. This necessitates us to commit them back in after merging `dev` to `master`.

Agreed @Jeff-Thompson12. What's a good alternative for the future? Create another function called `run_app_dev()` or `run_app_pre_auth()` that includes the arg? Or maybe the arg isn't even needed if we make a new function for it. `run_app_pre_auth()` could always skip authentication.

**Comment by Jeff-Thompson12** [comment]
Maybe philosophy around how it is being implemented should change. When created I was working with the idea that it should be completely removed from the code base, but the application is checking whether or not it is being run in production. We have code that completely bypasses authentication when running in a shiny test. If no argument is included in `run_app()` and the user cannot access any of the functionality when being run in production, we won't need to remove any code when pushing to production.

**Comment by AARON-CLARK** [comment]
> If no argument is included in `run_app()` and the user cannot access any of the functionality when being run in production, we won't need to remove any code when pushing to production.

@Jeff-Thompson12, are you suggesting no changes are needed?

**Comment by Jeff-Thompson12** [comment]
No, I think we would want to removed `pre_auth_user` from the list of arguments in `run_app()`. But I no longer think we need to remove code from other functions if we are checking if the app is being run in production (i.e. `isTRUE(get_golem_config("app_prod"))`)

**Comment by AARON-CLARK** [comment]
Are you saying we should permanently remove the `pre_auth_user` arg forever, or just when merging into `master`? If it's easier, feel free to open a PR with the changes needed. At the end of the day, we just want our merges from `dev` to `master` to be as effortless/painless as possible.

**Comment by Jeff-Thompson12** [comment]
> Are you saying we should permanently remove the `pre_auth_user` arg forever, or just when merging into `master`? If it's easier, feel free to open a PR with the changes needed. At the end of the day, we just want our merges from `dev` to `master` to be as effortless/painless as possible.

Being implemented with #429

**Pull request merged**
