### PR TITLE
Add download handler module

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Creates a download handler module for consistency between downloads in the database and report views.

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
I am still having trouble getting the DOCX and PDF downloads to work on all operating systems. Since this is a problem predating this PR, I am momentarily commenting those tests out.

**Comment by Jeff-Thompson12** [comment]
Converting to draft while I incorporate the edits from #339.

**Comment by Jeff-Thompson12** [comment]
I modified the test for the `databaseView` module to only check that the packages are being passed to the `downloadHandler` module.

**Review by Robert-Krajcik — APPROVED** [review]
Everything works and the test passes.  LGTM.

**Pull request merged**
