### PR TITLE
tests for `auto_font()` function

### PR DESCRIPTION
**Pull request by AARON-CLARK**
Working towards more test coverage on #295

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK The checks are pretty extensive for normal usage. Since we are exporting `auto_font()`, do we want to add any checks for invalid parameters?

**Comment by AARON-CLARK** [comment]
> Since we are exporting `auto_font()`, do we want to add any checks for invalid parameters?

@Jeff-Thompson12, that would be a good idea. But do you think we need to export it? Maybe we don't. User's don't need it to run the app. Maybe if we start exporting the functions used to build cards, we should export `auto_font()`. Thoughts?

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12 done!

**Comment by AARON-CLARK** [comment]
This seems silly. You can only have @examples for an exported function? Oh well, I removed them with commit 64b4c1b

image

**Comment by Jeff-Thompson12** [comment]
> This seems silly. You can only have @examples for an exported function?

@AARON-CLARK you can still have the examples if you use `@noRd` in the roxygen notes. That's what we have done with other functions.

**Comment by AARON-CLARK** [comment]
Okay @Jeff-Thompson12, this is ready for a re-review. I'll leave it without examples for now.

**Comment by AARON-CLARK** [comment]
Hey @Jeff-Thompson12, do you want to give this one final review & merge?

**Review by Jeff-Thompson12 — APPROVED** [review]
LGTM!

**Pull request merged**
