### PR TITLE
Update Github Actions

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #508

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
@AARON-CLARK I added you as well in case you wanted to take a look at the changes since I did edit the GHAs.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, the changes look good to me. So, `'renv'` is some sort keyword input for `setup-r`?

**Comment by Jeff-Thompson12** [comment]
Yes, it is a keyword to grab the R version from `renv.lock`.

**Review by AARON-CLARK — APPROVED** [review]
👍🏼 👍🏼

**Pull request merged**
