### PR TITLE
Fix a few bugs with choosing report options

### PR DESCRIPTION
**Pull request by Jeff-Thompson12**
Addresses #666 and #667

### CODE REVIEW

**Comment by Jeff-Thompson12** [comment]
This PR also re-envisions the usage of `trigger_events`. Instead of defining a reactive values object in the server and then passing that object to all modules, it assigns the object to `session$userData` so that all modules can access it without it being passed in the arguments.

**Review by Robert-Krajcik — CHANGES_REQUESTED** [review]
This really looks good, @Jeff-Thompson12 
But I noticed when a user has selected the "Package Dependencies" tab
and then jumps over to "Upload Packages" and uploads a package...
and then clicks on "Explore Metrics" on the "Summary of Uploaded Packages"
it takes you to the "Package Dependencies" tab
If the user is on the "Maintenance Metrics" tab, however, it works as expected.

**Comment by Robert-Krajcik** [comment]
I had left the "Explore Metrics" column in the "SUMMARY OF REMOVED PACKAGE(S)"
but removed the Action button.  If  you want to remove the column, that's fine.

**Comment by Jeff-Thompson12** [comment]
@Robert-Krajcik I have incorporated fixes for the bugs you found. I guess this PR has turned mostly into a squash bugs PR. Any other bugs?

**Comment by Robert-Krajcik** [comment]
No other bugs encountered, @Jeff-Thompson12 
I will give this a good run-through in a few minutes

**Review by Robert-Krajcik — APPROVED** [review]
Looks good to me!

**Pull request merged**
